# Generated by Django 4.2 on 2026-04-24 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Уникальный код (например: ОФ, ЦЕХ1, ОТД2)', max_length=10, unique=True, verbose_name='Код подразделения')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование подразделения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование основного средства')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('purchase_date', models.DateField(verbose_name='Дата покупки')),
                ('cost', models.DecimalField(decimal_places=2, help_text='В рублях', max_digits=12, verbose_name='Первоначальная стоимость')),
                ('depreciation_percent', models.IntegerField(default=0, help_text='От 0 до 100%', verbose_name='Процент износа (%)')),
                ('sequence_number', models.IntegerField(default=0, verbose_name='Порядковый номер в подразделении')),
                ('internal_code', models.CharField(blank=True, help_text='Автоматически генерируется (КодПодразд_ПорядковыйНомер)', max_length=50, unique=True, verbose_name='Код внутреннего учета')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='assets.department', verbose_name='Подразделение (место хранения)')),
            ],
            options={
                'verbose_name': 'Основное средство',
                'verbose_name_plural': 'Основные средства',
                'ordering': ['department', 'internal_code'],
            },
        ),
    ]
