# Generated by Django 5.2.11 on 2026-04-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('personal_phone', models.CharField(max_length=20, verbose_name='Личный телефон')),
                ('work_phone', models.CharField(blank=True, max_length=20, verbose_name='Рабочий телефон')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
                'permissions': [],
            },
        ),
    ]
