# Generated by Django 4.2 on 2026-04-24 14:30

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120, verbose_name='Марка автомобиля')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='Гос. номер')),
                ('production_year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('fuel_rate_per_km', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Норма расхода (л/км)')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['brand', 'plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars', models.ManyToManyField(related_name='drivers', to='transport.car', verbose_name='Автомобили')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
                'ordering': ['employee__full_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, unique=True, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='TripSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(verbose_name='Время выезда')),
                ('arrival_time', models.DateTimeField(verbose_name='Время заезда')),
                ('start_km', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Начальный километраж')),
                ('end_km', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Конечный километраж')),
                ('mileage', models.DecimalField(decimal_places=1, default=Decimal('0.0'), editable=False, max_digits=10, verbose_name='Пробег')),
                ('fuel_consumption', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=10, verbose_name='Расход топлива')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_sheets', to='transport.car', verbose_name='Автомобиль')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_sheets', to='transport.driver', verbose_name='Водитель')),
            ],
            options={
                'verbose_name': 'Путевой лист',
                'verbose_name_plural': 'Путевые листы',
                'ordering': ['-departure_time', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='transport.employee', verbose_name='Сотрудник'),
        ),
    ]
