# Generated by Django 4.2 on 2026-04-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Статья издержек')),
            ],
            options={
                'verbose_name': 'Статья издержек',
                'verbose_name_plural': 'Статьи издержек',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('expense_date', models.DateField(verbose_name='Дата операции')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory', verbose_name='Статья издержек')),
            ],
            options={
                'verbose_name': 'Издержка',
                'verbose_name_plural': 'Издержки',
                'ordering': ['-expense_date', 'id'],
            },
        ),
    ]
