# Generated by Django 5.2.11 on 2026-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Высокий'), (2, 'Обычный'), (3, 'Низкий')], default=2, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'запись журнала',
                'verbose_name_plural': 'записи журнала',
                'ordering': ['-created_at', 'title'],
            },
        ),
    ]
